//console.log([0] == [0])
//console.log([0] == ![0])
//console.log(Array(3) == ',,')

//console.log(typeof NaN)
//console.log(NaN == NaN)
//console.log(typeof null)
//console.log('string' instanceof String)
//console.log(9999999999999999)
//console.log(5 < Math.max())
//console.log([] + [])
//console.log([] + {})
//console.log({} + [])
//console.log({} + {})
//console.log(true * 4 === 4)
//console.log(true + true === 2)
//console.log(true === 1)
//console.log(! + [] + [] + ![])
